<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Rev-PF1JT47A" ignored="0" name="threetierJavaexample" tests="6" failures="2" timestamp="2022-02-01T14:21:04 EST" time="1.332" errors="0">
  <testcase name="createPlayer" time="0.927" classname="dev.revature.tests.playerdaos.PlayerDAOTests"/>
  <testcase name="deletePlayer" time="0.001" classname="dev.revature.tests.playerdaos.PlayerDAOTests">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at dev.revature.tests.playerdaos.PlayerDAOTests.deletePlayer(PlayerDAOTests.java:52)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- deletePlayer -->
  <testcase name="getAllPlayers" time="0.165" classname="dev.revature.tests.playerdaos.PlayerDAOTests"/>
  <testcase name="selectPlayerById" time="0.063" classname="dev.revature.tests.playerdaos.PlayerDAOTests"/>
  <testcase name="selectPlayerByIdFail" time="0.066" classname="dev.revature.tests.playerdaos.PlayerDAOTests"/>
  <testcase name="updatePlayer" time="0.001" classname="dev.revature.tests.playerdaos.PlayerDAOTests">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at dev.revature.tests.playerdaos.PlayerDAOTests.updatePlayer(PlayerDAOTests.java:47)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- updatePlayer -->
</testsuite> <!-- threetierJavaexample -->
